spring:
  application:
    name: "demo"
  h2:
    console:
      enabled: true
  mvc:
    throw-exception-if-no-handler-found: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: "/"
      path-mapping:
        health: "health"
  endpoint:
    health:
      enabled: true

