INSERT INTO USER values (1, 'User one');
INSERT INTO USER values (2, 'User two');
INSERT INTO USER values (3, 'User three');

INSERT INTO PAYMENT_TRANSACTION values (1, 'FIRST_PART_PAYED', 1);
INSERT INTO PAYMENT_TRANSACTION values (2, 'SECOND_PART_PAYED', 1);
INSERT INTO PAYMENT_TRANSACTION values (3, 'PAYED', 2);
INSERT INTO PAYMENT_TRANSACTION values (4, 'THIRD_PART_PAYED', 2);
INSERT INTO PAYMENT_TRANSACTION values (5, 'PAYED', 3);
INSERT INTO PAYMENT_TRANSACTION values (6, 'PAYED', 3);